config/routes.rb
Jarviis::Application.routes.draw do

  namespace :api do
    namespace :v1 do
      resource :attachments, only: :destroy

      resources :issues do
        member do
          post :resolve
          post :close
          post :wontfix
          post :open
          get  :comments

          resources :attachments, only: :create
        end

        collection do
          get :search
        end
      end

      resources :users, only: :index do
        collection do
          get :search
        end
      end

      resources :comments, only: [:create, :destroy]

      resources :teams, only: [:index, :show]

      resource :sprints, only: [:create, :update, :destroy, :show]
    end
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :users, only: [:index, :destroy, :edit, :update]
  end

  devise_for :users

  root to: "dashboard#index"

  get "/issues/:id" => "dashboard#index"
end

app/models/concerns/searchable/user.rb
module Searchable::User
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    settings index: { number_of_shards: 1 } do
      mappings dynamic: 'false' do
        indexes :id, type: "integer"
        indexes :email, boost: 10
        indexes :name
        indexes :username, boost: 10
        indexes :created_at, type: "date"
        indexes :updated_at, type: "date"
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Searchable::User

  before_save :set_auth_token

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  index_name "users_#{Rails.env}"

  has_many :assigned_issues, class_name: "Issue", foreign_key: "assignee_id"
  has_many :reported_issues, class_name: "Issue", foreign_key: "reporter_id"
  has_many :team_relationships
  has_many :teams, through: :team_relationships

  validates_uniqueness_of :username
  validates_presence_of   :username

  # Sets the aauthentication token to a SecureRandom without updating the
  # record to the database.
  def set_auth_token
    return if self.authentication_token.present?
    self.authentication_token = generate_auth_token
  end

  private

  def generate_auth_token
    loop do
      token = SecureRandom.hex
      break token unless self.class.exists?(authentication_token: token)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.includes(:teams).all
  end

  def edit
    @user = User.includes(:teams).find(params[:id])
  end

  def update
    @user_params = user_params

    if password_given?
      unless password_confirmation_match?
        flash[:error] = "Password did not match password confirmation"
        redirect_to :back and return
      end
    else
      @user_params.delete(:password)
      @user_params.delete(:password_confirmation)
    end

    @user = User.find(params[:id])
    @user.update_attributes(@user_params)

    redirect_to :back
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:success] = "#{@user.username} user was successfuly destroyed."
      forensic = Forensic.new
      forensic.user_id = current_user.id
      forensic.description = @user.to_json
      forensic.action = Forensic::ACTIONS[:destroy_user]
      forensic.save
    else
      flash[:error] = "Something went wrong while destroying user #{@user.username}"
    end

    redirect_to :back
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation,
                                 :admin, team_ids: [])
  end

  def password_given?
    user_params[:password].present?
  end

  def password_confirmation_match?
    user_params[:password] == user_params[:password_confirmation]
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController
  def index
    @users = User.all

    render json: @users
  end

  def search
    @users = User.search(params)

    render json: @users
  end
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Edit user <%= @user.username %></h3>
      <%= form_for @user, url: { action: "update" } do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :admin %>
          <%= f.check_box :admin %>
        </div>

        <div class="form-group">
          <%= f.label :team_ids, "Teams" %>
          <%= f.collection_select :team_ids, Team.order(:name), :id, :name, {}, multiple: true, class: "form-control chosen-choices" %>
        </div>

        <%= f.submit "Update", class: "create btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<script>
$(document).ready(function () {
  $(".chosen-choices").chosen();
  $(".chosen-choices").addClass('form-control');
  $("input.default").css('height', "28px");
});
</script>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Manage Users on this Jarviis</h3>
    </div>
    <div class="panel-body table-responsive">
      <table class="table table-hover">
        <thead>
          <th>User</th>
          <th>Username</th>
          <th>Email</th>
          <th>Admin</th>
          <th>Teams</th>
          <th>Actions</th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.username %></td>
              <td><%= user.email %></td>
              <td><%= "Yes" if user.admin? %></td>
              <td><%= user.teams.map(&:name).join(",") %></td>
              <td>
                <% if user.id != current_user.id %>
                  <%= link_to "Destroy", admin_user_path(user.id), method: :delete,
                    confirm: "Are you sure?", class: "small btn-primary btn-danger"%>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>